-- Generated by Oracle SQL Developer Data Modeler 17.4.0.355.2121
--   at:        2018-05-17 14:36:51 CEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE auto (
    kenteken    VARCHAR2(6) NOT NULL,
    dealernr    INTEGER,
    merk        VARCHAR2(50),
    type        VARCHAR2(50),
    dealernr2   INTEGER NOT NULL
);

ALTER TABLE auto ADD CONSTRAINT auto_pk PRIMARY KEY ( kenteken );

CREATE TABLE dealer (
    dealernr     INTEGER NOT NULL,
    dealernaam   VARCHAR2(50),
    kenteken     VARCHAR2(6) NOT NULL
);

ALTER TABLE dealer ADD CONSTRAINT dealer_pk PRIMARY KEY ( dealernr );

CREATE TABLE onderhoud (
    kenteken           VARCHAR2(6),
    werkplaatsnr       INTEGER NOT NULL,
    onderhoudsdatum    DATE,
    onderhoudskosten   NUMBER,
    auto_kenteken      VARCHAR2(6) NOT NULL
);

ALTER TABLE onderhoud ADD CONSTRAINT onderhoud_pk PRIMARY KEY ( werkplaatsnr );

CREATE TABLE werkplaats (
    werkplaatsnr    INTEGER NOT NULL,
    kenteken        VARCHAR2(6),
    wpnaam          VARCHAR2(50),
    auto_kenteken   VARCHAR2(6) NOT NULL
);

ALTER TABLE werkplaats ADD CONSTRAINT werkplaats_pk PRIMARY KEY ( werkplaatsnr );

ALTER TABLE auto
    ADD CONSTRAINT auto_dealer_fk FOREIGN KEY ( dealernr2 )
        REFERENCES dealer ( dealernr );

ALTER TABLE onderhoud
    ADD CONSTRAINT onderhoud_auto_fk FOREIGN KEY ( auto_kenteken )
        REFERENCES auto ( kenteken );

ALTER TABLE werkplaats
    ADD CONSTRAINT werkplaats_auto_fk FOREIGN KEY ( auto_kenteken )
        REFERENCES auto ( kenteken );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             4
-- CREATE INDEX                             0
-- ALTER TABLE                              7
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
